#!/bin/zsh

# Change default shell to zsh
if [[ ! $SHELL =~ zsh ]]
then
	chsh -s $(which zsh)
fi

# Add aliases to some dotfiles

rm -r ~/.zshrc
ln -s $(pwd)/.zshrc ~/.zshrc

rm -r ~/.config/awesome
ln -s $(pwd)/awesome ~/.config

rm -r ~/.Xresources
ln -s $(pwd)/.Xresources ~/.Xresources

rm -r ~/.vimrc
ln -s $(pwd)/.vimrc ~/.vimrc

xrdb ~/.Xresources
